services:
  web1:
    build: web-challenge-1
    ports:
      - "8001:8001"
  web2:
    build: web-challenge-2
    ports:
      - "8002:8002"
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      ONLINE_MODE: "FALSE" 
      ENABLE_COMMAND_BLOCK: "TRUE"
      ICON: "https://wiki.telavivmakers.org/images/b/bb/TAMI-ant.svg"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data